### ISSUE TITLE
Create Planning

### ISSUE THREAD

**Issue by estebanmino** [vigilant-octo-spoon/rails#3]
POST https://red-lab-sur.herokuapp.com/follows/1/planning

token: USER TOKEN

{
	"initiative_name": "Proyectos!!!",
	"objective": "Lograr hacer proyectos",
	"place": "Curso de diseño",
	"start_date": "2017-10-30",
	"finish_date": "2017-12-30"
}

Error 500

**Comment by estebanmino** [comment]
{
    "message": "Esto es información privada, usuario no encontrado"
}

**Comment by estebanmino** [comment]
ACTUALIZACION

Error 500 al tener la planificación creada e intentar nuevamente, funciona bien el CREATE.

**Comment by josehj** [comment]
error de respuesta, arreglado en rama v1.0
