### ISSUE TITLE
Create Binnacle

### ISSUE THREAD

**Issue by estebanmino** [vigilant-octo-spoon/rails#4]
https://red-lab-sur.herokuapp.com/follows/1/binnacle

Header token 

Body {
  "start_date": "2017-10-23",
  "finish_date": "2017-10-23",
  "objectives": "Presentar metodologia",
  "observations": "Los alu.....",
  "advances": "Las cosas han ido bien, destacamos que......",
  "obstacles": "Un grupo peq....",
  "ideas": "Pedirles a los alumn..."
}

error 500

{
    "message": "Esto es información privada"
}

**Comment by estebanmino** [comment]
ACTUALIZACION 

500 al crear bitacora

https://red-lab-sur.herokuapp.com/follows/1/binnacle

Token: ojKjfrRmJP_mVuxf_3sb

Body

{
"start_date": "2017-10-23",
"finish_date": "2017-10-23",
"objectives": "Presentar metodologia",
"observations": "Los alu.....",
"advances": "Las cosas han ido bien, destacamos que......",
"obstacles": "Un grupo peq....",
"ideas": "Pedirles a los alumn..."
}

Respuesta 500

Body 

{
    "message": "Bitacora creada exitosamente",
    "idBinnacle": 5
}

**Comment by josehj** [comment]
error de respuesta, arreglado en rama v1.0
